### ISSUE TITLE
Action<> event missing ReadBy search in the analyzer

### ISSUE THREAD

**Issue by xXTurnerLP** [VNGhostMans/dnSpyEx#10]
Recently I had to track where an Event was being called, but the event itself is assigned to another variable and dnSpy cant pick that up, so when you analyze it, it shows "Raised by" empty, even tho its called, just via a different variable. I had to print the stacktrace to find the caller.

Here is example definition and code:
Definition:
```cs
class1.event += global::class1.event_callback;
```

Caller's variable:
```cs
class2.event+= delegate(SomeParamType param)
{
        // (inside of delegate btw)
	Action<string, string> event= class1.event; // <-- this assign is not found by dnSpy
	if (event== null)
	{
		return;
	}
	event(param.member1, param.member2); // <-- the actual call
};
```

When the event of class1 is assigned to the actual callback code, it is never _directly_ called, instead, in another class its assigned to Action variable and called there, this cannot be found with dnSpy's analyzer

**Comment by VNGhostMans** [comment]
Hi, can you provide me a sample file so I can clearly see the error you raise?

**Comment by xXTurnerLP** [comment]
Hello, ~so I tried reproducing the scenario, but in my dummy dll I made i could actually find the event, but in the original dll I cannot~ I later changed the class' members to be static, and the same issue arised, **so i think its something to do with static members**
Here is a picture of how "Raised by" is empty, even tho the code is actually executed in the testApp tester
![image](https://user-images.githubusercontent.com/40324267/194112394-e6760c1c-0bde-41bd-9f65-6efe89fe106a.png)


I will provide my test dll [test1.zip](https://github.com/VNGhostMans/dnSpyEx/files/9717359/test1.zip)
(this is my testApp that calls the dll to test its output, which is "1234" followed by "1337")
```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace testApp
{
	internal class Program
	{
		static void Main(string[] args)
		{
		        var a = new test1.Class1(0);
			a.testMethod3_this_should_be_detected();
			a.testMethod4_this_is_NOT_detected();
		}
	}
}
```

And here is the ORIGINAL code im trying to reverse, its a dll from the Rust's (the game) server: [Facepunch.Console.zip](https://github.com/VNGhostMans/dnSpyEx/files/9717311/Facepunch.Console.zip) (note: Facepunch allows reversing of their server, this is how almost all mods/plugins for rust's server are made)

So to replicate the issue in Facepunch.Console.dll, go to class `ConsoleSystem` and find the static event member `OnReplicatedVarChanged`, press CTRL+SHIFT+R to analyze the member and you can see the "Raised by" section is empty.
However this event IS fired at runtime without reflection, and to see the caller go to method: `ConsoleSystem.Index.Initialize` and it should be on line 1025, the code is:
```cs
command2.OnValueChanged += delegate(ConsoleSystem.Command command)
{
	Action<string, string> onReplicatedVarChanged = ConsoleSystem.OnReplicatedVarChanged;
	if (onReplicatedVarChanged == null)
	{
		return;
	}
	onReplicatedVarChanged(command.FullName, command.String);
};
```
and this is not detected by dnSpy, if you need anything else let me know.

**Comment by VNGhostMans** [comment]
Hi, about your problem, please post your problem on the original [dnSpyEx](https://github.com/dnSpyEx/dnSpy) project developed by ElektrollKill. Thank you! I will close this issue as soon as you react emotionally to my answer.

**Comment by xXTurnerLP** [comment]
You can close it if you want, but please dont delete the issue, i have referenced it in the dnSpyEx repository because here ive included a lot of information and i dont wanna repeat myself there

**Comment by VNGhostMans** [comment]
OK. Please report this issue to ElektrollKill. I will close this issue. Thank you!

**Comment by VNGhostMans** [comment]
OK. Please report this issue to ElektrollKill. I will close this issue. Thank you!
