### ISSUE TITLE
Change method Editor add support for non printed (control characters) symbols

### ISSUE THREAD

**Issue by warchiefmarkus** [VNGhostMans/dnSpyEx#3]
Hi, while reversing obfuscated assembly (custom confuser ex) I faced the problem that wpf text edit input, used for renaming method name, cant show non printed os characters, so we cannot rename method without some hacks (like hotkeys ctrl + a, del). So for me i decide add some tricky functionality like second control input what will print method name in charcodes (like in code editor dnSpy). 
So you will see name even if it non printed, and also can edit non printed characters via charcodes, or replace with normal name.

So possible, will be usefully add same functionality to this version of dnSpy ? (also i can share my sources, but i think it may be bad style code :))
![2022-07-17_16-13](https://user-images.githubusercontent.com/12979968/179400239-d75ea594-dd02-4c6f-ad71-aa2d468b26da.png)

**Comment by VNGhostMans** [comment]
Hi, your problem is not in dnSpy, it is in the .NET file you are viewing. As far as I can see the file has been obfuscated by a .NET guard (from the picture you took I call that encoder Renamer). To solve it you just need to use de4dot to rename the assembly again, then you can continue your work without a hitch.

**Comment by warchiefmarkus** [comment]
I used de4dot and de4dot-cex but process of deobfuscation failed at the middle. So i cant get worked deobfuscated assembly and so must to edit obfuscated. Also I see no something tools before (encoder Renamer) so just improve dnSpy editor for me. I think extension for dnPsy (plugin) with such functionality will be usefully.

**Comment by VNGhostMans** [comment]
Hello. I repeat once again the problem you have is not with dnSpy.
de4dot should have done a good job of renaming assemblies. Make sure de4dot has full control (put the file you want to rename in a different drive than C drive).
