### ISSUE TITLE
The process cannot run because the process is attached

### ISSUE THREAD

**Issue by yyh9488** [VNGhostMans/dnSpyEx#7]
![image](https://user-images.githubusercontent.com/36093955/187124475-8e2da0b8-dd66-4bc3-a2e5-fa8e62eaba91.png)
The process cannot run because the process is attached. The donet.exe version is 6.0

**Comment by yyh9488** [comment]
You don't have this problem with VS2022 attaching, but VS2022 takes too long to load modules

**Comment by VNGhostMans** [comment]
Can you tell me what version you are using? Release or Beta?

**Comment by yyh9488** [comment]
version6.2 ，Release

**Comment by VNGhostMans** [comment]
Hi, please try to use the Beta version, if the Beta version still has the error condition that you are facing, I will report it to the developer to take a look. Thank!
