### ISSUE TITLE
Microsoft.Office.Interop. Excel code conversion partial error

### ISSUE THREAD

**Issue by zyyujq** [VNGhostMans/dnSpyEx#8]
The latest ilspy can convert the code correctly.（ILSPY V7.2.1.6856）
最新的ILSPY可以正确转换代码。

- Question 1：

C#

            objExcel = (Microsoft.Office.Interop.Excel.Application)Activator.CreateInstance(Type.GetTypeFromCLSID(new Guid("00024500-0000-0000-C000-000000000046")));

           objWorkbook = objExcel.Workbooks.Add(Missing.Value);
           //if (OneRainMonth.<>o__20.<>p__0 == null)
           //{
           //OneRainMonth.<>o__20.<>p__0 = CallSite<Func<CallSite, object, Worksheet>>.Create(Microsoft.CSharp.RuntimeBinder.Binder.Convert(CSharpBinderFlags.ConvertExplicit, typeof(Worksheet), typeof(OneRainMonth)));
           //}
           //objsheet = OneRainMonth.<>o__20.<>p__0.Target(OneRainMonth.<>o__20.<>p__0, objWorkbook.ActiveSheet);

           //The above comment is the error conversion of dnspy//上面注释的是dnSpy的错误转换

          objsheet = (Worksheet)(dynamic)objWorkbook.ActiveSheet;//Correct conversion//正确的转换

          objExcel.Visible = false;
          objsheet.DisplayAutomaticPageBreaks = true;

- Question 2：

C#

          objsheet.PageSetup.CenterHorizontally = true;
         objsheet.PageSetup.PrintTitleRows = "$1:$1";
         objsheet.PageSetup.PaperSize = XlPaperSize.xlPaperA4;
         objsheet.PageSetup.Orientation = XlPageOrientation.xlLandscape;
         //if (OneRainMonth.<>o__20.<>p__3 == null)
         //{
         //	OneRainMonth.<>o__20.<>p__3 = CallSite<Func<CallSite, object, Range>>.Create(Microsoft.CSharp.RuntimeBinder.Binder.Convert(CSharpBinderFlags.None, typeof(Range), typeof(OneRainMonth)));
         //}
         //Func<CallSite, object, Range> target = OneRainMonth.<>o__20.<>p__3.Target;
         //CallSite <>p__ = OneRainMonth.<>o__20.<>p__3;
         //if (OneRainMonth.<>o__20.<>p__2 == null)
         //{
         //	OneRainMonth.<>o__20.<>p__2 = CallSite<Func<CallSite, object, object, object, object>>.Create(Microsoft.CSharp.RuntimeBinder.Binder.GetIndex(CSharpBinderFlags.None, typeof(OneRainMonth), new CSharpArgumentInfo[]
         //	{
         //		CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.None, null),
         //		CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.None, null),
         //		CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.None, null)
         //	}));
         //}
         //Func<CallSite, object, object, object, object> target2 = OneRainMonth.<>o__20.<>p__2.Target;
         //CallSite <>p__2 = OneRainMonth.<>o__20.<>p__2;
         //if (OneRainMonth.<>o__20.<>p__1 == null)
         //{
         //	OneRainMonth.<>o__20.<>p__1 = CallSite<Func<CallSite, Worksheet, object>>.Create(Microsoft.CSharp.RuntimeBinder.Binder.GetMember(CSharpBinderFlags.ResultIndexed, "Range", typeof(OneRainMonth), new CSharpArgumentInfo[]
         //	{
         //		CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.UseCompileTimeType, null)
         //	}));
         //}
         //Range range2 = target(<>p__, target2(<>p__2, OneRainMonth.<>o__20.<>p__1.Target(OneRainMonth.<>o__20.<>p__1, objsheet), objsheet.Cells[1, 1], objsheet.Cells[1, 8]));

         //The above comment is the error conversion of dnspy//上面注释的是dnSpy的错误转换                                
        Range range2 = objsheet.Range[(dynamic)objsheet.Cells[1, 1], (dynamic)objsheet.Cells[1, 8]];//Correct conversion//正确的转换

         //if (OneRainMonth.<>o__20.<>p__6 == null)
         //{
         //	OneRainMonth.<>o__20.<>p__6 = CallSite<Func<CallSite, object, Range>>.Create(Microsoft.CSharp.RuntimeBinder.Binder.Convert(CSharpBinderFlags.None, typeof(Range), typeof(OneRainMonth)));
         //}
         //Func<CallSite, object, Range> target3 = OneRainMonth.<>o__20.<>p__6.Target;
         //CallSite <>p__3 = OneRainMonth.<>o__20.<>p__6;
         //if (OneRainMonth.<>o__20.<>p__5 == null)
         //{
         //	OneRainMonth.<>o__20.<>p__5 = CallSite<Func<CallSite, object, object, object, object>>.Create(Microsoft.CSharp.RuntimeBinder.Binder.GetIndex(CSharpBinderFlags.None, typeof(OneRainMonth), new CSharpArgumentInfo[]
         //	{
         //		CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.None, null),
         //		CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.None, null),
         //		CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.None, null)
         //	}));
         //}
         //Func<CallSite, object, object, object, object> target4 = OneRainMonth.<>o__20.<>p__5.Target;
         //CallSite <>p__4 = OneRainMonth.<>o__20.<>p__5;
         //if (OneRainMonth.<>o__20.<>p__4 == null)
         //{
         //	OneRainMonth.<>o__20.<>p__4 = CallSite<Func<CallSite, Worksheet, object>>.Create(Microsoft.CSharp.RuntimeBinder.Binder.GetMember(CSharpBinderFlags.ResultIndexed, "Range", typeof(OneRainMonth), new CSharpArgumentInfo[]
         //	{
         //		CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.UseCompileTimeType, null)
         //	}));
         //}
         //Range range3 = target3(<>p__3, target4(<>p__4, OneRainMonth.<>o__20.<>p__4.Target(OneRainMonth.<>o__20.<>p__4, objsheet), objsheet.Cells[1, 9], objsheet.Cells[1, 26]));

         //The above comment is the error conversion of dnspy//上面注释的是dnSpy的错误转换
        Range range3= objsheet.Range[(dynamic)objsheet.Cells[1, 9], (dynamic)objsheet.Cells[1, 26]];//Correct conversion//正确的转换

**Comment by VNGhostMans** [comment]
Hello, please use English to communicate with me. Thank!
Regarding your problem, currently, dnSpy uses ILSpy v2.4 so the output won't be clean because of C# development. Currently the developer (ElektroKill) is trying to update ILSpy v7 for dnSpy, but he is having a hard time because he has to rewrite the entire ILSpy code because dnSpy uses dnlib, and ILSpy does not. The upgrade process can take a long time depending on the complexity of the code. You can use ILSpy for best code reading when dnSpy can't work.

**Comment by zyyujq** [comment]
Thank you for your reply!
Of course, the problem should be in the reference of ilspy library.

**Comment by zyyujq** [comment]
Looking forward to elektrokill updating the code
