### ISSUE TITLE
how to show modules tab ?

### ISSUE THREAD

**Issue by elmagekmosaad** [VNGhostMans/dnSpyEx#9]
how to show modules tab ?

**Comment by VNGhostMans** [comment]
First, you need to start dnSpy's debugger (don't ask me how to start it). Then press Ctrl + Alt + U, the Modules tab will appear at the bottom.

**Comment by elmagekmosaad** [comment]
> First, you need to start dnSpy's debugger (don't ask me how to start it). Then press Ctrl + Alt + U, the Modules tab will appear at the bottom.

hhhhhh
don't worry
but i ask because i already try Ctrl+Alt+U but no thing happend

**Comment by elmagekmosaad** [comment]
Can you help me and do that by team viewer or any disk ?

**Comment by elmagekmosaad** [comment]
thanks it's work when start debug thank you ♥
